'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class GivingHistoryDisplay2

    '''<summary>
    '''pageError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pageError As Global.Blackbaud.Web.Content.Core.Controls.BBLabel

    '''<summary>
    '''ValidPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidPage As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''tabActiveGiftsDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabActiveGiftsDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkActiveTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkActiveTab As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''tabHistoryGiftsDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabHistoryGiftsDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkHistoryTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkHistoryTab As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblFilterHelpText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFilterHelpText As Global.Blackbaud.Web.Content.Core.Controls.BBLabel

    '''<summary>
    '''ValidationSummary1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummary1 As Global.Blackbaud.Web.Content.Core.Controls.BBValidationSummary

    '''<summary>
    '''lblTruncatedRecordsHelpText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTruncatedRecordsHelpText As Global.Blackbaud.Web.Content.Core.Controls.BBLabel

    '''<summary>
    '''DatePickerLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DatePickerLabel As Global.Blackbaud.Web.Content.Core.Controls.BBLabel

    '''<summary>
    '''datePicker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents datePicker As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''divSpecificDateRange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSpecificDateRange As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dpStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpStartDate As Global.Blackbaud.Web.Content.Core.Controls.DatePicker

    '''<summary>
    '''dpEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpEndDate As Global.Blackbaud.Web.Content.Core.Controls.DatePicker

    '''<summary>
    '''fundPickerPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fundPickerPanel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''FundPickerLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FundPickerLabel As Global.Blackbaud.Web.Content.Core.Controls.BBLabel

    '''<summary>
    '''fundPicker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fundPicker As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''GroupPickerLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GroupPickerLabel As Global.Blackbaud.Web.Content.Core.Controls.BBLabel

    '''<summary>
    '''groupPicker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents groupPicker As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFilter As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mTabControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mTabControl As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''VwActiveHistoryTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VwActiveHistoryTab As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''ActiveHistoryHelpTextLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActiveHistoryHelpTextLabel As Global.Blackbaud.Web.Content.Core.Controls.BBLabel

    '''<summary>
    '''givingHistoryActiveOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents givingHistoryActiveOnly As Global.Blackbaud.CustomFx.WrappedParts.WebParts.GivingHistory2Control

    '''<summary>
    '''VwHistoryTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VwHistoryTab As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''FullHistoryHelpTextLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FullHistoryHelpTextLabel As Global.Blackbaud.Web.Content.Core.Controls.BBLabel

    '''<summary>
    '''givingHistoryAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents givingHistoryAll As Global.Blackbaud.CustomFx.WrappedParts.WebParts.GivingHistory2Control
End Class
