'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class GivingHistoryEditor2

    '''<summary>
    '''HiddenAvailableColumnData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenAvailableColumnData As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenUsedColumnData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenUsedColumnData As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenUsedColumnString control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenUsedColumnString As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenSelectedGiftTypeIDs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenSelectedGiftTypeIDs As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenSelectedCampaignIDs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenSelectedCampaignIDs As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenSelectedFundIDs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenSelectedFundIDs As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenSelectedAppealIDs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenSelectedAppealIDs As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenSelectedRecGiftEditFilterFundIDs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenSelectedRecGiftEditFilterFundIDs As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HiddenSelectedRecGiftEditFilterAppealIDs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenSelectedRecGiftEditFilterAppealIDs As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''ResultsPerPageLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResultsPerPageLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ResultsPerPageDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResultsPerPageDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''divGiftsFiltering control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divGiftsFiltering As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblBackOfficeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBackOfficeName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GiftsDefaultRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GiftsDefaultRadioButton As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''GiftsCustomRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GiftsCustomRadioButton As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''GiftsREQueryRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GiftsREQueryRadioButton As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lblBackOfficeCFA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBackOfficeCFA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBackOfficeCFA2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBackOfficeCFA2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGiftTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGiftTypes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tr_CampaignFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_CampaignFilter As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblBackOfficeCampaign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBackOfficeCampaign As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCampaigns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCampaigns As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBackOfficeFund control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBackOfficeFund As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFunds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFunds As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAppeals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppeals As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQueryBackOfficeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQueryBackOfficeName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBOQueryType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBOQueryType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GiftQueryLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GiftQueryLink As Global.Blackbaud.Web.Content.Portal.QueryLink

    '''<summary>
    '''SoftCreditDisplayCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SoftCreditDisplayCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblSoftCreditHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSoftCreditHelp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PendingTransactionDisplayCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PendingTransactionDisplayCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divUnpaidEvents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divUnpaidEvents As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cbUnpaidEvents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbUnpaidEvents As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divChooseColumnsSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divChooseColumnsSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCustomColumnsHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomColumnsHelp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ColumnDefaulRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ColumnDefaulRadioButton As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''ColumnCustomRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ColumnCustomRadioButton As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lblDefaultPanelHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDefaultPanelHelp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGiftType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGiftType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFundColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFundColumn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAmount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SpecificColumnsUK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SpecificColumnsUK As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lblCustomPanelHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomPanelHelp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkIncludeSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIncludeSummary As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblGiftTotalsHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGiftTotalsHelp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''summarySubOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents summarySubOptions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkIncludeTotalsCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIncludeTotalsCurrency As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkIncludeGiftTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIncludeGiftTotal As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''SoftCreditsPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SoftCreditsPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkIncludeSoftCreditTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIncludeSoftCreditTotal As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''SoftCreditTotalLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SoftCreditTotalLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''chkIncludeHardCreditTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIncludeHardCreditTotal As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''HardCreditTotalLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HardCreditTotalLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''chkIncludeGiftAidTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIncludeGiftAidTotal As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''PledgeTotalCheckBoxPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PledgeTotalCheckBoxPanel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkIncludePledgeTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIncludePledgeTotal As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divPendingTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPendingTotal As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkIncludePendingTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIncludePendingTotal As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''PledgeBalanceTotalPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PledgeBalanceTotalPanel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkIncludeBalanceTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIncludeBalanceTotal As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''PledgePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PledgePanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblPledgePaymentPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPledgePaymentPage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PledgePaymentPageLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PledgePaymentPageLink As Global.Blackbaud.Web.Content.Portal.PageLink

    '''<summary>
    '''UnpaidEventPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UnpaidEventPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblUnpaidEventPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUnpaidEventPage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UnpaidEventPageLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UnpaidEventPageLink As Global.Blackbaud.Web.Content.Portal.PageLink

    '''<summary>
    '''pnlAdditionalDonation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAdditionalDonation As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblRecGiftAdditionalDonationPageLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecGiftAdditionalDonationPageLink As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RecGiftAdditionalDonationPageLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecGiftAdditionalDonationPageLink As Global.Blackbaud.Web.Content.Portal.PageLink

    '''<summary>
    '''RecurringGiftPaymentPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecurringGiftPaymentPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblRecGiftPaymentPageLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecGiftPaymentPageLink As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RecGiftPaymentPageLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecGiftPaymentPageLink As Global.Blackbaud.Web.Content.Portal.PageLink

    '''<summary>
    '''divRecurringGiftUpdates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divRecurringGiftUpdates As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rdoRecGftUpdFilterAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoRecGftUpdFilterAll As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdoRecGftUpdFilterCustom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoRecGftUpdFilterCustom As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdoRecGftUpdFilterQuery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoRecGftUpdFilterQuery As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lblRecGftUpdBOCFA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecGftUpdBOCFA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRecGftUpdBOCFA2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecGftUpdBOCFA2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRecGftUpdBOFundsText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecGftUpdBOFundsText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRecGftUpdFundsChosen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecGftUpdFundsChosen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRecGftUpdAppealsChosen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecGftUpdAppealsChosen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRecGftUpdBOText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecGftUpdBOText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RecGftUpdFilterQueryLnk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecGftUpdFilterQueryLnk As Global.Blackbaud.Web.Content.Portal.QueryLink

    '''<summary>
    '''chkAllowRecurringAmountUpdates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAllowRecurringAmountUpdates As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblAllowRecurringAmountUpdatesHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAllowRecurringAmountUpdatesHelp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divSubOptionAllowRecAmtUpdates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSubOptionAllowRecAmtUpdates As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblAllowRecAmtUpdatesMinAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAllowRecAmtUpdatesMinAmt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAllowRecAmtUpdatesMinAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAllowRecAmtUpdatesMinAmt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkAllowFrequencyUpdates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAllowFrequencyUpdates As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblAllowFrequencyUpdatesHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAllowFrequencyUpdatesHelp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divSubOptionAllowFrequencyUpdates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSubOptionAllowFrequencyUpdates As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''generalRecurrenceRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents generalRecurrenceRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''specificRecurrenceRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents specificRecurrenceRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lblRecGiftFrequencyGridError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecGiftFrequencyGridError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RecurrenceDataGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecurrenceDataGrid As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''RecurringGiftSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecurringGiftSchedule As Global.Blackbaud.AppFx.ContentManagement.UI.WebControls.RecurringGiftSchedule

    '''<summary>
    '''AddRecurrenceButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddRecurrenceButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RecurringGiftScheduleStartDateCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecurringGiftScheduleStartDateCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RecurringGiftScheduleEndDateCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecurringGiftScheduleEndDateCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkAllowPaymentTypeUpdates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAllowPaymentTypeUpdates As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblAllowPaymentTypeUpdatesHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAllowPaymentTypeUpdatesHelp As Global.System.Web.UI.WebControls.Label
End Class
