'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class GivingHistory2Control

    '''<summary>
    '''GivingHistoryContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GivingHistoryContainer As Global.Blackbaud.Web.Content.Portal.UpdateControls.StyledUpdatePanel

    '''<summary>
    '''lblGridHelpText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGridHelpText As Global.Blackbaud.Web.Content.Core.Controls.BBLabel

    '''<summary>
    '''ExportContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExportContainer As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ExportTitleLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExportTitleLabel As Global.Blackbaud.Web.Content.Core.Controls.BBLabel

    '''<summary>
    '''ExportDropDownButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExportDropDownButton As Global.Blackbaud.Web.Content.Core.Controls.BBLinkButton

    '''<summary>
    '''ExportListPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExportListPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''PdfLinkButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PdfLinkButton As Global.Blackbaud.Web.Content.Core.Controls.BBLinkButton

    '''<summary>
    '''PdfLinkText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PdfLinkText As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CsvLinkButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CsvLinkButton As Global.Blackbaud.Web.Content.Core.Controls.BBLinkButton

    '''<summary>
    '''CsvLinkText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CsvLinkText As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''grid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grid As Global.Blackbaud.Web.Content.Portal.GivingHistory.GivingHistoryGrid

    '''<summary>
    '''pager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pager1 As Global.Blackbaud.Web.Content.Portal.Components.Pager

    '''<summary>
    '''lblSummaryHelpText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSummaryHelpText As Global.Blackbaud.Web.Content.Core.Controls.BBLabel

    '''<summary>
    '''summary1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents summary1 As Global.System.Web.UI.WebControls.GridView
End Class
